{
 "title": "API Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "description": "Request duration distribution for HTTP requests to the MiniTwit API",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(api_request_duration_bucket{job=\"minitwit_api\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Count Rate",
   "type": "stat",
   "description": "The rate of processed HTTP requests by the MiniTwit API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_request_count{job=\"minitwit_api\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "description": "The CPU load percentage for the MiniTwit API",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_cpu_load{job=\"minitwit_api\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}